sudo: required
dist: trusty
language: rust

rust:
  # Nightly required only for -Z flag in setup.py
  - nightly

matrix:
  fast_finish: true

python:
  - "3.5"
  - "3.6"

cache: cargo

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - gcc-7
      - libssl-dev

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda create -q -n test-environment python=3.5 -y
  - source activate test-environment
  - pip install -r requirements.txt

  # Setup modern gcc & g++ compiler
  - sudo ln -sf /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -sf /usr/bin/g++-7 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7

  - gcc -v && g++ -v

script:
  - cargo build
  - cargo test
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/lumberjack/rust python setup.py test
