language: rust

rust:
  - nightly
  #- stable

python:
  - "3.5"
  - "3.6"

# TODO: Add matrix to test with multiple python versions for lumber-jack build
cache: cargo

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda create -q -n test-environment python=3.5 -y
  - source activate test-environment
  - pip install -r requirements.txt
  - gcc -v

script:
  - cargo build
  - cargo test
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/lumberjack/rust python setup.py test

